// tmp/original-docs/DocsScrollTracker.tsx
'use client';

import { useState, useEffect } from 'react';
import DocsSidebar from './DocsSidebar';

interface Section {
  id: string;
  title: string;
}

interface DocsScrollTrackerProps {
  sections: Section[];
}

export default function DocsScrollTracker({ sections }: DocsScrollTrackerProps) {
  const [activeSection, setActiveSection] = useState('overview');

  useEffect(() => {
    const handleScroll = () => {
      const scrollPosition = window.scrollY + 90;
      
      for (const section of sections) {
        const element = document.getElementById(section.id);
        if (element) {
          const { offsetTop, offsetHeight } = element;
          if (scrollPosition >= offsetTop && scrollPosition < offsetTop + offsetHeight) {
            setActiveSection(section.id);
            break;
          }
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    handleScroll();
    
    return () => window.removeEventListener('scroll', handleScroll);
  }, [sections]);

  return (
    <DocsSidebar 
      sections={sections} 
      activeSection={activeSection} 
    />
  );
}

// src/lib/components/docs/DocsScrollTracker.svelte
<script lang="ts">
  import { browser } from '$app/environment';
  import DocsSidebar from './DocsSidebar.svelte';

  export interface Section {
    id: string;
    title: string;
  }

  interface DocsScrollTrackerProps {
    sections: Section[];
  }

  let { sections }: DocsScrollTrackerProps = $props();

  let activeSection = $state('overview');

  const HEADER_OFFSET = 90;

  function updateActiveSection() {
    if (!browser) return;
    
    const scrollY = window.scrollY + HEADER_OFFSET;
    
    // Get all section elements
    const sectionElements = sections
      .map(section => ({
        ...section,
        element: document.getElementById(section.id)
      }))
      .filter(section => section.element !== null) as Array<Section & { element: HTMLElement }>;

    if (sectionElements.length === 0) return;

    // Find the current active section
    let currentActiveSection = sectionElements[0].id;

    for (let i = 0; i < sectionElements.length; i++) {
      const current = sectionElements[i];
      const next = sectionElements[i + 1];

      const currentTop = current.element.offsetTop;
      const nextTop = next ? next.element.offsetTop : Infinity;

      if (scrollY >= currentTop && scrollY < nextTop) {
        currentActiveSection = current.id;
        break;
      }
    }

    // Handle edge case for last section
    const lastSection = sectionElements[sectionElements.length - 1];
    if (scrollY >= lastSection.element.offsetTop) {
      currentActiveSection = lastSection.id;
    }

    if (activeSection !== currentActiveSection) {
      activeSection = currentActiveSection;
    }
  }

  let throttleTimeout: number | null = null;

  function handleScroll() {
    if (throttleTimeout) return;
    
    throttleTimeout = window.setTimeout(() => {
      updateActiveSection();
      throttleTimeout = null;
    }, 16); // ~60fps
  }

  // Use $effect instead of onMount/onDestroy for Svelte 5
  $effect(() => {
    if (!browser) return;
    
    // Initial active section detection
    updateActiveSection();
    
    // Add scroll listener
    window.addEventListener('scroll', handleScroll, { passive: true });
    
    // Also listen for resize to recalculate positions
    window.addEventListener('resize', updateActiveSection, { passive: true });

    // Cleanup function (equivalent to onDestroy)
    return () => {
      if (throttleTimeout) {
        clearTimeout(throttleTimeout);
      }
      window.removeEventListener('scroll', handleScroll);
      window.removeEventListener('resize', updateActiveSection);
    };
  });
</script>

<DocsSidebar {sections} {activeSection} />
