// src/lib/components/docs/shared/Accordion.svelte
<script lang="ts">
  import { slide } from 'svelte/transition';
  import { quintOut } from 'svelte/easing';

  // Accordion item interface
  import type { Snippet } from 'svelte';

  interface AccordionItem {
    id: string;
    title: string;
    content: Snippet;
  }

  interface AccordionProps {
    items: AccordionItem[];
    defaultOpen?: string[];
    allowMultiple?: boolean;
    class?: string;
  }

  let {
    items,
    defaultOpen = [],
    allowMultiple = true,
    class: className = ''
  }: AccordionProps = $props();

  // State management using Svelte 5 runes
  let openItems = $state(new Set(defaultOpen));

  // Toggle accordion item
  function toggleItem(itemId: string) {
    const newOpenItems = new Set(openItems);
    
    if (newOpenItems.has(itemId)) {
      // Close the item
      newOpenItems.delete(itemId);
    } else {
      // Open the item
      if (!allowMultiple) {
        // If only single item allowed, clear all others
        newOpenItems.clear();
      }
      newOpenItems.add(itemId);
    }
    
    openItems = newOpenItems;
  }

  // Handle keyboard navigation
  function handleKeydown(event: KeyboardEvent, itemId: string) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      toggleItem(itemId);
    }
  }

  // Check if item is open
  function isOpen(itemId: string): boolean {
    return openItems.has(itemId);
  }
</script>

<div class="w-full space-y-2 {className}">
  {#each items as item (item.id)}
    <div class="border border-border rounded-lg overflow-hidden bg-background/50 backdrop-blur-sm">
      <!-- Accordion Header -->
      <button
        class="w-full px-6 py-4 text-left flex items-center justify-between
               hover:bg-muted/30 focus-visible:outline-none focus-visible:ring-2 
               focus-visible:ring-primary focus-visible:ring-offset-2 
               transition-all duration-200 ease-out group"
        onclick={() => toggleItem(item.id)}
        onkeydown={(e) => handleKeydown(e, item.id)}
        aria-expanded={isOpen(item.id)}
        aria-controls="accordion-content-{item.id}"
        id="accordion-button-{item.id}"
      >
        <!-- Title -->
        <span class="text-sm font-medium text-foreground pr-4">
          {item.title}
        </span>
        
        <!-- Expand/Collapse Icon -->
        <div class="flex-shrink-0 transition-transform duration-200 ease-out {isOpen(item.id) ? 'rotate-180' : 'rotate-0'}">
          <svg 
            class="w-5 h-5 text-muted-foreground group-hover:text-foreground" 
            fill="none" 
            viewBox="0 0 24 24" 
            stroke="currentColor"
            aria-hidden="true"
          >
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
          </svg>
        </div>
      </button>

      <!-- Accordion Content -->
      {#if isOpen(item.id)}
        <div
          id="accordion-content-{item.id}"
          class="border-t border-border"
          role="region"
          aria-labelledby="accordion-button-{item.id}"
          transition:slide={{ duration: 300, easing: quintOut }}
        >
          <div class="px-6 py-4">
            {@render item.content()}
          </div>
        </div>
      {/if}
    </div>
  {/each}
</div>

// tmp/original-docs/shared/Accordion.tsx
'use client';

import { useState } from 'react';

interface AccordionItem {
  id: string;
  title: string;
  content: React.ReactNode;
}

interface AccordionProps {
  items: AccordionItem[];
  defaultOpen?: string;
}

export default function Accordion({ items, defaultOpen }: AccordionProps) {
  const [openItems, setOpenItems] = useState<string[]>(defaultOpen ? [defaultOpen] : []);

  const toggleItem = (id: string) => {
    setOpenItems(prev => 
      prev.includes(id) 
        ? prev.filter(item => item !== id)
        : [...prev, id]
    );
  };

  return (
    <div className="space-y-2 not-prose">
      {items.map((item) => (
        <div key={item.id} className="border border-border rounded-lg overflow-hidden">
          <button
            onClick={() => toggleItem(item.id)}
            className="w-full px-6 py-4 flex items-center justify-between bg-background hover:bg-muted/50 transition-colors duration-200 focus:ring-2 focus:ring-primary focus:outline-none"
          >
            <span className="font-medium text-foreground text-left">{item.title}</span>
            <svg
              className={`w-5 h-5 text-muted-foreground transition-transform duration-200 ${
                openItems.includes(item.id) ? 'rotate-180' : ''
              }`}
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>
          
          <div
            className={`transition-all duration-300 ease-in-out ${
              openItems.includes(item.id)
                ? 'max-h-96 opacity-100'
                : 'max-h-0 opacity-0 overflow-hidden'
            }`}
          >
            <div className="px-6 py-4 bg-muted border-t border-border">
              {item.content}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
