// src/lib/components/docs/shared/FeatureCard.svelte
<script lang="ts">
  import type { ComponentType } from 'svelte';

  interface FeatureCardProps {
    icon?: ComponentType;
    title: string;
    description: string;
    highlight?: boolean;
    class?: string;
  }

  let {
    icon,
    title,
    description,
    highlight = false,
    class: className = ''
  }: FeatureCardProps = $props();
</script>

<div 
  class="group relative h-full transition-all duration-300 ease-out hover:-translate-y-0.5 {className}"
>
  <!-- Card container -->
  <div class="relative bg-background/50 border border-border rounded-xl h-full overflow-hidden shadow-lg hover:shadow-xl transition-all duration-300 backdrop-blur-sm hover:border-primary/50">
    
    <!-- Card content -->
    <div class="p-6 h-full flex flex-col">
      
      <!-- Icon -->
      {#if icon}
        <div class="mb-4 flex-shrink-0">
          <div class="inline-flex items-center justify-center w-12 h-12 rounded-lg bg-primary/10 border border-primary/30 transition-all duration-300 group-hover:bg-primary/20 group-hover:border-primary/50">
            <svelte:component this={icon} class="w-6 h-6 text-primary" />
          </div>
        </div>
      {/if}
      
      <!-- Title -->
      <h3 class="text-xl font-bold text-foreground mb-3 tracking-tight flex-shrink-0 transition-colors duration-300 {highlight ? 'group-hover:text-primary' : ''}">
        {title}
      </h3>
      
      <!-- Description -->
      <p class="text-base text-muted-foreground leading-relaxed flex-grow transition-colors duration-300 group-hover:text-foreground">
        {description}
      </p>
    </div>
    
    <!-- Hover overlay gradient -->
    <div class="absolute inset-0 bg-gradient-to-br from-primary/[0.02] to-primary/[0.01] opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none" />
  </div>
</div>

// tmp/original-docs/shared/FeatureCard.tsx
interface FeatureCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
  highlight?: boolean;
}

export default function FeatureCard({ icon, title, description, highlight = false }: FeatureCardProps) {
  return (
    <div className={`
      relative p-6 rounded-xl transition-all duration-200
      ${highlight 
        ? 'bg-gradient-to-br from-primary/10 to-emerald/10 border-2 border-primary/30 shadow-lg hover:shadow-xl hover:border-primary/50' 
        : 'bg-background border border-border hover:border-border/70 hover:shadow-md'
      }
    `}>
      <div className="flex items-start gap-4">
        <div className={`
          flex-shrink-0 p-3 rounded-lg
          ${highlight ? 'bg-primary/20 text-primary' : 'bg-muted text-muted-foreground'}
        `}>
          {icon}
        </div>
        <div>
          <h4 className="text-lg font-semibold text-foreground mb-2">{title}</h4>
          <p className="text-muted-foreground leading-relaxed">{description}</p>
        </div>
      </div>
    </div>
  );
}
